name: CI

on:
  pull_request_target:
    types: [ opened, reopened, ready_for_review, synchronize ]
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  Run-Common-CI:
    uses: dm-vdo/vdo-org-actions/.github/workflows/ci.yaml@main
    with:
      logfile: logs-${{ github.event.repository.owner.login }}-${{ github.event.repository.name }}-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}
      run-public-build: true
      public-build-action: make all
      run-public-tests: true
      public-tests-action: make oss-jenkins
      public-tests-failure-action: |
          cd logs
          for i in *;
          do
            if [ -d "$i" ]; then
              cd $i
              for file in *::*.log;
              do
                [ -e "$file" ] || continue
                mv "${file}" "${file/::/--}"
              done
              cd ..
            else
              mv "${i}" "${i/::/--}"
            fi
          done
      run-private-build: true
      private-build-action: make all
      run-private-tests: true
      private-tests-action: make jenkins
    secrets: inherit
   
